version: "3.5"

services:
  mongo:
    container_name: mongo_dev
    image: mongo
    ports:
      - "27017:27017"
  mongo_seed:
    container_name: mongo_seed
    build: .
    depends_on:
      - mongo
