version: "3.5"

services:
  mongo_dev:
    container_name: mongo_dev
    image: mongo:latest
    ports:
      - 27017:27017
    networks:
      - dev

  mongo_seed:
    container_name: mongo_seed
    build: .
    networks:
      - dev
    depends_on:
      - mongo_dev

networks:
  dev:
    driver: bridge
    name: dev