image: docker:stable

services:
  - mongo:latest

cache:
  paths:
  - node_modules/

variables:
  IMAGE_NAME: ravecat/mendeleev_api
  APP_CONTAINER: mendeleev_api
  DB_HOST: mongo

stages:
  - test
  - build
  - deploy

test:
  image: node:10.13-alpine
  stage: test
  tags:
    - docker
  dependencies: []
  script:
    - npm i -g yarn 
    - yarn
    - yarn lint
    - ./node_modules/.bin/mocha --opts .mocharc

build:
  stage: build
  tags:
    - docker
  only:
    - develop
  script: 
    - echo "$(echo "$REGISTRY_PASSWORD" | base64 -d)" | docker login -u "$(echo "$REGISTRY_USER" | base64 -d)" --password-stdin
    - docker build -t $IMAGE_NAME:develop .
    - docker push $IMAGE_NAME:develop
    - docker logout

deploy_develop:
  stage: deploy
  tags:
    - docker
  only:
    - develop
  variables:
    IMAGE: $IMAGE_NAME:develop
    PORT: 3000
  script:
    - apk add py-pip
    - apk add python-dev libffi-dev openssl-dev gcc libc-dev make
    - pip install docker-compose
    - docker image prune -f
    - docker-compose build --no-cache
    - docker-compose up -d --build
