stages:
  - test
  - deploy

.docker-login: &docker-login
  - docker -v
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

test_app:
  image: node:15.8-alpine3.13
  stage: test
  tags:
    - docker
  services:
    - name: mongo:3.6.22-xenial
      alias: mongo
  variables: 
    DB_HOST: mongo
  dependencies: []
  script:
    - yarn
    - yarn test:app

test_lint:
  image: node:15.8-alpine3.13
  stage: test
  tags:
    - docker
  dependencies: []
  script:
    - yarn
    - yarn test:commit
    - yarn test:lint
    - yarn test:prettier

approve_deploy_branch:
  stage: deploy
  allow_failure: true
  when: manual
  except:
    refs:
      - master
  trigger:
    include: .config/.gitlab-ci.deploy-branch.yml

deploy:
  stage: deploy
  image: ${REGISTRY}/${REGISTRY_NAMESPACE}/node:15.7-docker-compose1.27
  tags:
    - docker
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
  before_script:
    - *docker-login
  variables:
    PROJECT: mendeleev-api
    HOST: ${DOMAIN_PATH}.${DOMAIN_NAME}
    DOCKER_GATEWAY_NETWORK: $DOCKER_GATEWAY_NETWORK
    IMAGE: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}
    RELEASE: master-${CI_COMMIT_SHORT_SHA}
    DB_HOST: host.docker.internal
  script:
    - docker build --no-cache -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
    - yarn start
