image: docker:stable

services:
  - mongo:latest

cache:
  paths:
    - node_modules/

variables:
  IMAGE: ravecat/mendeleev_api
  APP_CONTAINER: mendeleev_api
  DB_HOST: mongo

stages:
  - test
  - build
  - deploy

test_api:
  image: node:10.13-alpine
  stage: test
  tags:
    - docker
  dependencies: []
  script:
    - npm i -g yarn
    - yarn
    - ./node_modules/.bin/mocha --opts .mocharc

test_lint:
  image: node:10.13-alpine
  stage: test
  tags:
    - docker
  dependencies: []
  script:
    - npm i -g yarn
    - yarn
    - yarn lint
    - yarn prettier

build:
  stage: build
  tags:
    - docker
  only:
    - develop
  script:
    - echo "$(echo "$REGISTRY_PASSWORD" | base64 -d)" | docker login -u "$(echo "$REGISTRY_USER" | base64 -d)" --password-stdin
    - docker build -t $IMAGE .
    - docker push $IMAGE
    - docker logout

deploy:
  stage: deploy
  tags:
    - docker
  only:
    - master
  variables:
    PORT: 3000
  script:
    - echo "$(echo "$REGISTRY_PASSWORD" | base64 -d)" | docker login -u "$(echo "$REGISTRY_USER" | base64 -d)" --password-stdin
    - apk add py-pip
    - apk add python-dev libffi-dev openssl-dev gcc libc-dev make
    - pip install docker-compose
    - docker-compose build --no-cache
    - docker-compose up -d --build
    - docker logout
