version: "3.5"

services:
  mongo:
    container_name: mongo
    restart: always
    image: mongo:latest
    ports:
      - 27017:27017
    networks:
      - prod

  app:
    container_name: app
    restart: always
    build: .
    ports:
      - 3001:3001
    depends_on:
      - mongo
    networks:
      - prod

networks:
  prod:
    name: prod
    driver: bridge