version: "3.5"

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    networks:
      - prod

  app:
    container_name: app
    build: .
    environment:
      - NODE_ENV=production
      - DB_HOST=mongo
      - PORT=3000
    restart: always
    build: .
    ports:
      - 3000:3000
    depends_on:
      - mongo
    networks:
      - prod

networks:
  prod:
    name: prod
    driver: bridge