version: "3.5"

services:
  express:
    container_name: express
    image: mendeleev_srv_express
    restart: always
    build: .
    ports:
      - "3001:3001"
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
