version: "3.5"

services:
  mongo_dev:
    container_name: mongo_dev
    image: mongo:latest
    networks:
      - dev

  mongo_seed:
    image: mongo:latest
    container_name: mongo_seed
    volumes:
      - .:/app
    command: mongoimport --host mongo_dev --db mendeleev --collection elements --drop --file /app/elements.json --jsonArray
    networks:
      - dev
    depends_on:
      - mongo_dev
  
  app_dev:
    container_name: app_dev
    environment:
      - DB_HOST=mongo_dev
    volumes:
      - .:/app
    working_dir: /app
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 3001:3001
    networks:
      - dev
    depends_on:
      - mongo_dev

networks:
  dev:
    driver: bridge
    name: dev