version: "3.5"

services:
  mongo:
    container_name: ${DB_HOST}
    image: mongo:latest
    networks:
      - production

  app:
    container_name: ${APP_CONTAINER}
    image: ${IMAGE}
    environment:
      - PORT
      - DB_HOST
      - DB_NAME
      - DB_PORT
      - ERROR_STATUS
      - BODY_LIMIT
    restart: always
    ports:
      - ${PORT}:3000
    depends_on:
      - ${DB_HOST}
    networks:
      - production

networks:
  production:
    name: production
    driver: bridge