version: "3.5"

services:
  mongo_test:
    container_name: mongo_test
    image: mongo:latest
    networks:
      - test

  app_test:
    image: node:10.13-alpine
    command: sh -c "yarn && ./node_modules/.bin/mocha --opts .mocharc"
    container_name: app_test
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - NODE_ENV=test
      - DB_HOST=mongo_test
    depends_on:
      - mongo_test
    networks:
      - test

networks:
  test:
    driver: bridge
    name: test
