version: '3.5'

services:
  app:
    networks:
      - gateway
    extra_hosts:
      - "host.docker.internal:host-gateway"
    labels:
      - traefik.http.routers.${CI_COMMIT_SHORT_SHA}.rule=Host(`${HOST:?"SET HOST"}`)
      - traefik.http.services.${CI_COMMIT_SHORT_SHA}.loadbalancer.server.port=3000
      - traefik.http.middlewares.${CI_COMMIT_SHORT_SHA}.compress=true
      - traefik.http.routers.${CI_COMMIT_SHORT_SHA}.middlewares=${CI_COMMIT_SHORT_SHA}

networks:
  gateway:
    name: "${DOCKER_GATEWAY_NETWORK}"
    external: true

