version: '3.5'

services:
  mongo:
    container_name: ${PROJECT:-app}-${RELEASE}-mongo
    image: mongo:3.6.22-xenial
    restart: on-failure
    networks:
      - internal

  mongo_seed:
    image: mongo:3.6.22-xenial
    container_name: ${PROJECT:-app}-${RELEASE}-mongo-seed
    volumes:
      - ../:/app
    command: sh -c "mongorestore --host ${PROJECT:-app}-${RELEASE}-mongo --gzip --archive=/app/mongo/initialData.gz"
    networks:
      - internal
    depends_on:
      - mongo
      
  app:
    command: "yarn dev:app"
    working_dir: /app
    environment:
      DB_HOST: ${PROJECT:-app}-${RELEASE}-mongo
    volumes:
      - ../:/app
    ports:
      - ${PORT:-3000}:3000
    depends_on:
      - mongo
    networks:
      - internal

networks:
  internal:
    name: ${PROJECT:-app}-${RELEASE}-network
    driver: bridge
