version: '3.5'

services:
  mongo_test:
    container_name: mongo_test
    image: mongo:3.6.22-xenial
    networks:
      - test

  app_test:
    image: node:15.8-alpine3.13
    command: "yarn test:app"
    container_name: app_test
    volumes:
      - ../:/app
    working_dir: /app
    environment:
      - NODE_ENV=test
      - DB_HOST=mongo_test
    depends_on:
      - mongo_test
    networks:
      - test

networks:
  test:
    driver: bridge
    name: mendeleev-api-test
