version: '3.5'

services:
  mongo:
    container_name: "mendeleev-api-mongo-${RELEASE}"
    image: mongo:3.6.22-xenial
    restart: on-failure
    networks:
      - mendeleev-api

  mendeleev-api:
    container_name: "mendeleev-api-${RELEASE}"
    image: "${CI_REGISTRY_IMAGE}:${RELEASE}"
    environment:
      - NODE_ENV
      - PORT
      - DB_HOST
      - DB_NAME
      - DB_PORT
    restart: always
    depends_on:
      - mongo
    labels:
      - traefik.http.routers.mendeleev-api.rule=Host(`${RELEASE}.api.mendeleev.${DOMAIN_NAME}`)
    networks:
      - mendeleev-api
      - gateway

networks:
  mendeleev-api:
    name: "mendeleev-api-${RELEASE}"
    driver: bridge
  gateway:
    name: "${DOCKER_GATEWAY_NETWORK}"
    external: true
